const TRACKS = [
  { id: "kick", label: "Kick", key: "K", volume: 0.9, pattern: [1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0] },
  { id: "snare", label: "Snare", key: "S", volume: 0.72, pattern: [0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0] },
  { id: "hat", label: "Hat", key: "H", volume: 0.34, pattern: [1,0,1,0,1,0,1,1,1,0,1,0,1,0,1,1] },
  { id: "clap", label: "Clap", key: "C", volume: 0.44, pattern: [0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0] },
];
const state = { tempo: 96, swing: 0, root: "C", currentStep: 0, playing: false, timer: null, audio: null, bass: [1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0] };
const $ = (selector) => document.querySelector(selector);
const steps = Array.from({ length: 16 }, (_, index) => index);

function buildGrid() {
  $("#stepNumbers").innerHTML = steps.map((step) => `<span>${step + 1}</span>`).join("");
  $("#sequencer").innerHTML = TRACKS.map((track) => `<div class="track-row"><div class="track-name"><b>${track.key}</b>${track.label}</div><div class="steps">${steps.map((step) => `<button class="step ${track.pattern[step] ? "active" : ""}" data-track="${track.id}" data-step="${step}" type="button" aria-label="${track.label}, step ${step + 1}"></button>`).join("")}</div></div>`).join("");
  $("#bassNotes").innerHTML = steps.map((step) => `<button class="bass-step ${state.bass[step] ? "active" : ""}" data-bass-step="${step}" type="button" aria-label="Bass, step ${step + 1}"></button>`).join("");
  $("#mixerControls").innerHTML = TRACKS.map((track) => `<label class="mixer-row">${track.label}<input data-volume="${track.id}" type="range" min="0" max="100" value="${Math.round(track.volume * 100)}" /><output>${Math.round(track.volume * 100)}</output></label>`).join("");
}

function ensureAudio() { if (!state.audio) state.audio = new (window.AudioContext || window.webkitAudioContext)(); if (state.audio.state === "suspended") state.audio.resume(); return state.audio; }
function noiseBuffer(context) { const buffer = context.createBuffer(1, context.sampleRate * .14, context.sampleRate); const data = buffer.getChannelData(0); for (let i = 0; i < data.length; i++) data[i] = Math.random() * 2 - 1; return buffer; }
function sound(track, when = 0, context = ensureAudio(), destination = context.destination) {
  const gain = context.createGain(); gain.gain.value = track.volume; gain.connect(destination);
  if (track.id === "kick") { const osc = context.createOscillator(); const amp = context.createGain(); osc.frequency.setValueAtTime(145, when); osc.frequency.exponentialRampToValueAtTime(45, when + .18); amp.gain.setValueAtTime(1, when); amp.gain.exponentialRampToValueAtTime(.001, when + .22); osc.connect(amp).connect(gain); osc.start(when); osc.stop(when + .23); }
  else { const source = context.createBufferSource(); const filter = context.createBiquadFilter(); const amp = context.createGain(); source.buffer = noiseBuffer(context); filter.type = track.id === "hat" ? "highpass" : "bandpass"; filter.frequency.value = track.id === "hat" ? 7000 : 1350; const length = track.id === "hat" ? .045 : track.id === "clap" ? .16 : .12; amp.gain.setValueAtTime(track.id === "hat" ? .55 : 1, when); amp.gain.exponentialRampToValueAtTime(.001, when + length); source.connect(filter).connect(amp).connect(gain); source.start(when); source.stop(when + length); }
}
function bassSound(when = 0, context = ensureAudio(), destination = context.destination) { const rootFreq = { C:65.41, "D#":77.78, F:87.31, G:98, "A#":116.54 }[state.root]; const osc = context.createOscillator(); const sub = context.createOscillator(); const amp = context.createGain(); const filter = context.createBiquadFilter(); osc.type = "sawtooth"; sub.type = "sine"; osc.frequency.value = rootFreq; sub.frequency.value = rootFreq / 2; filter.type = "lowpass"; filter.frequency.value = 480; amp.gain.setValueAtTime(.001, when); amp.gain.exponentialRampToValueAtTime(.26, when + .018); amp.gain.exponentialRampToValueAtTime(.001, when + .28); osc.connect(filter); sub.connect(filter); filter.connect(amp).connect(destination); osc.start(when); sub.start(when); osc.stop(when + .3); sub.stop(when + .3); }
function updatePlayhead() { document.querySelectorAll(".playing").forEach((node) => node.classList.remove("playing")); document.querySelectorAll(`[data-step="${state.currentStep}"], [data-bass-step="${state.currentStep}"]`).forEach((node) => node.classList.add("playing")); }
function tick() { const context = ensureAudio(); const now = context.currentTime; TRACKS.filter((track) => track.pattern[state.currentStep]).forEach((track) => sound(track, now)); if (state.bass[state.currentStep]) bassSound(now); updatePlayhead(); const seconds = 60 / state.tempo / 4; const swung = state.currentStep % 2 ? seconds * (1 + state.swing / 100) : seconds * (1 - state.swing / 100); state.currentStep = (state.currentStep + 1) % 16; state.timer = window.setTimeout(tick, swung * 1000); }
function start() { if (state.playing) return; ensureAudio(); state.playing = true; $("#playButton").textContent = "❚❚"; tick(); }
function stop() { state.playing = false; clearTimeout(state.timer); state.currentStep = 0; document.querySelectorAll(".playing").forEach((node) => node.classList.remove("playing")); $("#playButton").textContent = "▶"; }
function project() { return { tracks: TRACKS.map((track) => ({ id: track.id, pattern: track.pattern, volume: track.volume })), bass: state.bass, tempo: state.tempo, swing: state.swing, root: state.root, name: $("#projectName").value.trim() || "Untitled sketch" }; }
function save() { localStorage.setItem("loso-media-studio", JSON.stringify(project())); $("#saveNote").textContent = "Saved on this device."; }
function load() { try { const saved = JSON.parse(localStorage.getItem("loso-media-studio")); if (!saved) return; TRACKS.forEach((track) => { const data = saved.tracks?.find((entry) => entry.id === track.id); if (data) { track.pattern = data.pattern; track.volume = data.volume; } }); state.bass = saved.bass || state.bass; state.tempo = saved.tempo || state.tempo; state.swing = saved.swing || 0; state.root = saved.root || state.root; $("#projectName").value = saved.name || "After-hours sketch"; $("#tempo").value = state.tempo; $("#swing").value = state.swing; $("#rootNote").value = state.root; $("#tempoValue").textContent = `${state.tempo} BPM`; $("#swingValue").textContent = `${state.swing}%`; } catch {} }
async function exportWav() { const bars = 2; const duration = (60 / state.tempo / 4) * 16 * bars + 1; const rate = 44100; const offline = new OfflineAudioContext(1, Math.ceil(rate * duration), rate); const master = offline.createGain(); master.gain.value = .85; master.connect(offline.destination); const stepLength = 60 / state.tempo / 4; for (let bar = 0; bar < bars; bar++) steps.forEach((step) => { const at = (bar * 16 + step) * stepLength; TRACKS.filter((track) => track.pattern[step]).forEach((track) => sound(track, at, offline, master)); if (state.bass[step]) bassSound(at, offline, master); }); const buffer = await offline.startRendering(); const wav = wavBlob(buffer); const link = document.createElement("a"); link.href = URL.createObjectURL(wav); link.download = `${project().name.replace(/[^a-z0-9]+/gi,"-").toLowerCase() || "loso-loop"}.wav`; link.click(); URL.revokeObjectURL(link.href); $("#saveNote").textContent = "Two-bar WAV exported."; }
function wavBlob(buffer) { const samples = buffer.getChannelData(0); const out = new ArrayBuffer(44 + samples.length * 2); const view = new DataView(out); const write = (offset, text) => [...text].forEach((char, index) => view.setUint8(offset + index, char.charCodeAt(0))); write(0,"RIFF"); view.setUint32(4,36 + samples.length * 2,true); write(8,"WAVEfmt "); view.setUint32(16,16,true); view.setUint16(20,1,true); view.setUint16(22,1,true); view.setUint32(24,buffer.sampleRate,true); view.setUint32(28,buffer.sampleRate*2,true); view.setUint16(32,2,true); view.setUint16(34,16,true); write(36,"data"); view.setUint32(40,samples.length*2,true); samples.forEach((sample,index) => view.setInt16(44 + index*2,Math.max(-1,Math.min(1,sample))*0x7fff,true)); return new Blob([out],{type:"audio/wav"}); }

load(); buildGrid();
$("#sequencer").addEventListener("click", (event) => { const button = event.target.closest(".step"); if (!button) return; const track = TRACKS.find((item) => item.id === button.dataset.track); const step = Number(button.dataset.step); track.pattern[step] = track.pattern[step] ? 0 : 1; button.classList.toggle("active", Boolean(track.pattern[step])); });
$("#bassNotes").addEventListener("click", (event) => { const button = event.target.closest(".bass-step"); if (!button) return; const step = Number(button.dataset.bassStep); state.bass[step] = state.bass[step] ? 0 : 1; button.classList.toggle("active", Boolean(state.bass[step])); });
$("#mixerControls").addEventListener("input", (event) => { const input = event.target.closest("[data-volume]"); if (!input) return; const track = TRACKS.find((item) => item.id === input.dataset.volume); track.volume = Number(input.value) / 100; input.nextElementSibling.textContent = input.value; });
$("#playButton").addEventListener("click", () => state.playing ? stop() : start()); $("#stopButton").addEventListener("click", stop);
$("#tempo").addEventListener("input", (event) => { state.tempo = Number(event.target.value); $("#tempoValue").textContent = `${state.tempo} BPM`; }); $("#swing").addEventListener("input", (event) => { state.swing = Number(event.target.value); $("#swingValue").textContent = `${state.swing}%`; }); $("#rootNote").addEventListener("change", (event) => { state.root = event.target.value; });
$("#clearButton").addEventListener("click", () => { TRACKS.forEach((track) => track.pattern.fill(0)); state.bass.fill(0); buildGrid(); });
$("#randomButton").addEventListener("click", () => { TRACKS.forEach((track, index) => track.pattern = steps.map((step) => index === 0 ? step % 4 === 0 || (Math.random() > .84) : index === 1 ? step % 8 === 4 || (Math.random() > .92) : Math.random() > (index === 2 ? .46 : .78) ? 1 : 0)); state.bass = steps.map((step) => step % 4 === 0 && Math.random() > .2 ? 1 : 0); buildGrid(); });
$("#saveButton").addEventListener("click", save); $("#exportButton").addEventListener("click", exportWav);
document.addEventListener("keydown", (event) => { if (["INPUT","TEXTAREA","SELECT"].includes(document.activeElement.tagName)) return; const track = TRACKS.find((item) => item.key === event.key.toUpperCase()); if (track) sound(track); if (event.code === "Space") { event.preventDefault(); state.playing ? stop() : start(); } });
document.querySelectorAll("[data-drum]").forEach((button) => button.addEventListener("click", () => {
  const track = TRACKS.find((item) => item.id === button.dataset.drum);
  if (track) sound(track);
}));
